/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TrackComplaintRouteRouteImport } from './routes/TrackComplaintRoute'
import { Route as SubmitComplaintRouteRouteImport } from './routes/SubmitComplaintRoute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ComplaintDetailRouteIdRouteImport } from './routes/ComplaintDetailRoute.$id'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin/complaints/index'
import { Route as AdminSettingsSubcategoriesRouteImport } from './routes/admin/settings/subcategories'
import { Route as AdminSettingsSlaRouteImport } from './routes/admin/settings/sla'
import { Route as AdminSettingsOrganizationsRouteImport } from './routes/admin/settings/organizations'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsFormsRouteImport } from './routes/admin/settings/forms'
import { Route as AdminSettingsAuditLogsRouteImport } from './routes/admin/settings/audit-logs'
import { Route as AdminSettingsTermPrivacyRouteImport } from './routes/admin/settings/Term-Privacy'
import { Route as AdminReportsSummaryRouteImport } from './routes/admin/reports/summary'
import { Route as AdminReportsSlaRouteImport } from './routes/admin/reports/sla'
import { Route as AdminReportsInvestigationRouteImport } from './routes/admin/reports/investigation'
import { Route as AdminReportsExecutiveRouteImport } from './routes/admin/reports/executive'
import { Route as AdminReportsAuditLogRouteImport } from './routes/admin/reports/audit-log'
import { Route as AdminComplaintsSensitiveRouteImport } from './routes/admin/complaints/sensitive'
import { Route as AdminComplaintsInvestigationRouteImport } from './routes/admin/complaints/investigation'
import { Route as AdminComplaintsIntakeRouteImport } from './routes/admin/complaints/intake'
import { Route as AdminComplaintsExtensionsRouteImport } from './routes/admin/complaints/extensions'
import { Route as AdminComplaintsDocumentsRouteImport } from './routes/admin/complaints/documents'
import { Route as AdminComplaintsAssignmentRouteImport } from './routes/admin/complaints/assignment'
import { Route as AdminSettingsUsersIndexRouteImport } from './routes/admin/settings/users/index'
import { Route as AdminSettingsRolesIndexRouteImport } from './routes/admin/settings/roles/index'
import { Route as AdminSettingsCategoriesIndexRouteImport } from './routes/admin/settings/categories/index'
import { Route as AdminComplaintsApprovalIndexRouteImport } from './routes/admin/complaints/approval/index'
import { Route as AdminSettingsUsersNewRouteImport } from './routes/admin/settings/users/new'
import { Route as AdminSettingsRolesNewRouteImport } from './routes/admin/settings/roles/new'
import { Route as AdminSettingsCategoriesNewRouteImport } from './routes/admin/settings/categories/new'
import { Route as AdminComplaintsEditIdRouteImport } from './routes/admin/complaints/edit/$id'
import { Route as AdminSettingsUsersEditIdRouteImport } from './routes/admin/settings/users/edit/$id'
import { Route as AdminSettingsRolesEditIdRouteImport } from './routes/admin/settings/roles/edit/$id'
import { Route as AdminSettingsCategoriesEditIdRouteImport } from './routes/admin/settings/categories/edit/$id'
import { Route as AdminComplaintsApprovalEditIdRouteImport } from './routes/admin/complaints/approval/edit/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackComplaintRouteRoute = TrackComplaintRouteRouteImport.update({
  id: '/TrackComplaintRoute',
  path: '/TrackComplaintRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitComplaintRouteRoute = SubmitComplaintRouteRouteImport.update({
  id: '/SubmitComplaintRoute',
  path: '/SubmitComplaintRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintDetailRouteIdRoute = ComplaintDetailRouteIdRouteImport.update({
  id: '/ComplaintDetailRoute/$id',
  path: '/ComplaintDetailRoute/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin/reports/',
  path: '/admin/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/admin/complaints/',
  path: '/admin/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsSubcategoriesRoute =
  AdminSettingsSubcategoriesRouteImport.update({
    id: '/admin/settings/subcategories',
    path: '/admin/settings/subcategories',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsSlaRoute = AdminSettingsSlaRouteImport.update({
  id: '/admin/settings/sla',
  path: '/admin/settings/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsOrganizationsRoute =
  AdminSettingsOrganizationsRouteImport.update({
    id: '/admin/settings/organizations',
    path: '/admin/settings/organizations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/admin/settings/notifications',
    path: '/admin/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsFormsRoute = AdminSettingsFormsRouteImport.update({
  id: '/admin/settings/forms',
  path: '/admin/settings/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsAuditLogsRoute = AdminSettingsAuditLogsRouteImport.update({
  id: '/admin/settings/audit-logs',
  path: '/admin/settings/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsTermPrivacyRoute =
  AdminSettingsTermPrivacyRouteImport.update({
    id: '/admin/settings/Term-Privacy',
    path: '/admin/settings/Term-Privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsSummaryRoute = AdminReportsSummaryRouteImport.update({
  id: '/admin/reports/summary',
  path: '/admin/reports/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsSlaRoute = AdminReportsSlaRouteImport.update({
  id: '/admin/reports/sla',
  path: '/admin/reports/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsInvestigationRoute =
  AdminReportsInvestigationRouteImport.update({
    id: '/admin/reports/investigation',
    path: '/admin/reports/investigation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsExecutiveRoute = AdminReportsExecutiveRouteImport.update({
  id: '/admin/reports/executive',
  path: '/admin/reports/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsAuditLogRoute = AdminReportsAuditLogRouteImport.update({
  id: '/admin/reports/audit-log',
  path: '/admin/reports/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsSensitiveRoute =
  AdminComplaintsSensitiveRouteImport.update({
    id: '/admin/complaints/sensitive',
    path: '/admin/complaints/sensitive',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsInvestigationRoute =
  AdminComplaintsInvestigationRouteImport.update({
    id: '/admin/complaints/investigation',
    path: '/admin/complaints/investigation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsIntakeRoute = AdminComplaintsIntakeRouteImport.update({
  id: '/admin/complaints/intake',
  path: '/admin/complaints/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsExtensionsRoute =
  AdminComplaintsExtensionsRouteImport.update({
    id: '/admin/complaints/extensions',
    path: '/admin/complaints/extensions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsDocumentsRoute =
  AdminComplaintsDocumentsRouteImport.update({
    id: '/admin/complaints/documents',
    path: '/admin/complaints/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsAssignmentRoute =
  AdminComplaintsAssignmentRouteImport.update({
    id: '/admin/complaints/assignment',
    path: '/admin/complaints/assignment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsUsersIndexRoute = AdminSettingsUsersIndexRouteImport.update({
  id: '/admin/settings/users/',
  path: '/admin/settings/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRolesIndexRoute = AdminSettingsRolesIndexRouteImport.update({
  id: '/admin/settings/roles/',
  path: '/admin/settings/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsCategoriesIndexRoute =
  AdminSettingsCategoriesIndexRouteImport.update({
    id: '/admin/settings/categories/',
    path: '/admin/settings/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsApprovalIndexRoute =
  AdminComplaintsApprovalIndexRouteImport.update({
    id: '/admin/complaints/approval/',
    path: '/admin/complaints/approval/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsUsersNewRoute = AdminSettingsUsersNewRouteImport.update({
  id: '/admin/settings/users/new',
  path: '/admin/settings/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRolesNewRoute = AdminSettingsRolesNewRouteImport.update({
  id: '/admin/settings/roles/new',
  path: '/admin/settings/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsCategoriesNewRoute =
  AdminSettingsCategoriesNewRouteImport.update({
    id: '/admin/settings/categories/new',
    path: '/admin/settings/categories/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsEditIdRoute = AdminComplaintsEditIdRouteImport.update({
  id: '/admin/complaints/edit/$id',
  path: '/admin/complaints/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsUsersEditIdRoute =
  AdminSettingsUsersEditIdRouteImport.update({
    id: '/admin/settings/users/edit/$id',
    path: '/admin/settings/users/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsRolesEditIdRoute =
  AdminSettingsRolesEditIdRouteImport.update({
    id: '/admin/settings/roles/edit/$id',
    path: '/admin/settings/roles/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingsCategoriesEditIdRoute =
  AdminSettingsCategoriesEditIdRouteImport.update({
    id: '/admin/settings/categories/edit/$id',
    path: '/admin/settings/categories/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminComplaintsApprovalEditIdRoute =
  AdminComplaintsApprovalEditIdRouteImport.update({
    id: '/admin/complaints/approval/edit/$id',
    path: '/admin/complaints/approval/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SubmitComplaintRoute': typeof SubmitComplaintRouteRoute
  '/TrackComplaintRoute': typeof TrackComplaintRouteRoute
  '/auth': typeof AuthRoute
  '/ComplaintDetailRoute/$id': typeof ComplaintDetailRouteIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/complaints/assignment': typeof AdminComplaintsAssignmentRoute
  '/admin/complaints/documents': typeof AdminComplaintsDocumentsRoute
  '/admin/complaints/extensions': typeof AdminComplaintsExtensionsRoute
  '/admin/complaints/intake': typeof AdminComplaintsIntakeRoute
  '/admin/complaints/investigation': typeof AdminComplaintsInvestigationRoute
  '/admin/complaints/sensitive': typeof AdminComplaintsSensitiveRoute
  '/admin/reports/audit-log': typeof AdminReportsAuditLogRoute
  '/admin/reports/executive': typeof AdminReportsExecutiveRoute
  '/admin/reports/investigation': typeof AdminReportsInvestigationRoute
  '/admin/reports/sla': typeof AdminReportsSlaRoute
  '/admin/reports/summary': typeof AdminReportsSummaryRoute
  '/admin/settings/Term-Privacy': typeof AdminSettingsTermPrivacyRoute
  '/admin/settings/audit-logs': typeof AdminSettingsAuditLogsRoute
  '/admin/settings/forms': typeof AdminSettingsFormsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/organizations': typeof AdminSettingsOrganizationsRoute
  '/admin/settings/sla': typeof AdminSettingsSlaRoute
  '/admin/settings/subcategories': typeof AdminSettingsSubcategoriesRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/complaints/edit/$id': typeof AdminComplaintsEditIdRoute
  '/admin/settings/categories/new': typeof AdminSettingsCategoriesNewRoute
  '/admin/settings/roles/new': typeof AdminSettingsRolesNewRoute
  '/admin/settings/users/new': typeof AdminSettingsUsersNewRoute
  '/admin/complaints/approval/': typeof AdminComplaintsApprovalIndexRoute
  '/admin/settings/categories/': typeof AdminSettingsCategoriesIndexRoute
  '/admin/settings/roles/': typeof AdminSettingsRolesIndexRoute
  '/admin/settings/users/': typeof AdminSettingsUsersIndexRoute
  '/admin/complaints/approval/edit/$id': typeof AdminComplaintsApprovalEditIdRoute
  '/admin/settings/categories/edit/$id': typeof AdminSettingsCategoriesEditIdRoute
  '/admin/settings/roles/edit/$id': typeof AdminSettingsRolesEditIdRoute
  '/admin/settings/users/edit/$id': typeof AdminSettingsUsersEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SubmitComplaintRoute': typeof SubmitComplaintRouteRoute
  '/TrackComplaintRoute': typeof TrackComplaintRouteRoute
  '/auth': typeof AuthRoute
  '/ComplaintDetailRoute/$id': typeof ComplaintDetailRouteIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/complaints/assignment': typeof AdminComplaintsAssignmentRoute
  '/admin/complaints/documents': typeof AdminComplaintsDocumentsRoute
  '/admin/complaints/extensions': typeof AdminComplaintsExtensionsRoute
  '/admin/complaints/intake': typeof AdminComplaintsIntakeRoute
  '/admin/complaints/investigation': typeof AdminComplaintsInvestigationRoute
  '/admin/complaints/sensitive': typeof AdminComplaintsSensitiveRoute
  '/admin/reports/audit-log': typeof AdminReportsAuditLogRoute
  '/admin/reports/executive': typeof AdminReportsExecutiveRoute
  '/admin/reports/investigation': typeof AdminReportsInvestigationRoute
  '/admin/reports/sla': typeof AdminReportsSlaRoute
  '/admin/reports/summary': typeof AdminReportsSummaryRoute
  '/admin/settings/Term-Privacy': typeof AdminSettingsTermPrivacyRoute
  '/admin/settings/audit-logs': typeof AdminSettingsAuditLogsRoute
  '/admin/settings/forms': typeof AdminSettingsFormsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/organizations': typeof AdminSettingsOrganizationsRoute
  '/admin/settings/sla': typeof AdminSettingsSlaRoute
  '/admin/settings/subcategories': typeof AdminSettingsSubcategoriesRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/complaints/edit/$id': typeof AdminComplaintsEditIdRoute
  '/admin/settings/categories/new': typeof AdminSettingsCategoriesNewRoute
  '/admin/settings/roles/new': typeof AdminSettingsRolesNewRoute
  '/admin/settings/users/new': typeof AdminSettingsUsersNewRoute
  '/admin/complaints/approval': typeof AdminComplaintsApprovalIndexRoute
  '/admin/settings/categories': typeof AdminSettingsCategoriesIndexRoute
  '/admin/settings/roles': typeof AdminSettingsRolesIndexRoute
  '/admin/settings/users': typeof AdminSettingsUsersIndexRoute
  '/admin/complaints/approval/edit/$id': typeof AdminComplaintsApprovalEditIdRoute
  '/admin/settings/categories/edit/$id': typeof AdminSettingsCategoriesEditIdRoute
  '/admin/settings/roles/edit/$id': typeof AdminSettingsRolesEditIdRoute
  '/admin/settings/users/edit/$id': typeof AdminSettingsUsersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/SubmitComplaintRoute': typeof SubmitComplaintRouteRoute
  '/TrackComplaintRoute': typeof TrackComplaintRouteRoute
  '/auth': typeof AuthRoute
  '/ComplaintDetailRoute/$id': typeof ComplaintDetailRouteIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/complaints/assignment': typeof AdminComplaintsAssignmentRoute
  '/admin/complaints/documents': typeof AdminComplaintsDocumentsRoute
  '/admin/complaints/extensions': typeof AdminComplaintsExtensionsRoute
  '/admin/complaints/intake': typeof AdminComplaintsIntakeRoute
  '/admin/complaints/investigation': typeof AdminComplaintsInvestigationRoute
  '/admin/complaints/sensitive': typeof AdminComplaintsSensitiveRoute
  '/admin/reports/audit-log': typeof AdminReportsAuditLogRoute
  '/admin/reports/executive': typeof AdminReportsExecutiveRoute
  '/admin/reports/investigation': typeof AdminReportsInvestigationRoute
  '/admin/reports/sla': typeof AdminReportsSlaRoute
  '/admin/reports/summary': typeof AdminReportsSummaryRoute
  '/admin/settings/Term-Privacy': typeof AdminSettingsTermPrivacyRoute
  '/admin/settings/audit-logs': typeof AdminSettingsAuditLogsRoute
  '/admin/settings/forms': typeof AdminSettingsFormsRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/organizations': typeof AdminSettingsOrganizationsRoute
  '/admin/settings/sla': typeof AdminSettingsSlaRoute
  '/admin/settings/subcategories': typeof AdminSettingsSubcategoriesRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/complaints/edit/$id': typeof AdminComplaintsEditIdRoute
  '/admin/settings/categories/new': typeof AdminSettingsCategoriesNewRoute
  '/admin/settings/roles/new': typeof AdminSettingsRolesNewRoute
  '/admin/settings/users/new': typeof AdminSettingsUsersNewRoute
  '/admin/complaints/approval/': typeof AdminComplaintsApprovalIndexRoute
  '/admin/settings/categories/': typeof AdminSettingsCategoriesIndexRoute
  '/admin/settings/roles/': typeof AdminSettingsRolesIndexRoute
  '/admin/settings/users/': typeof AdminSettingsUsersIndexRoute
  '/admin/complaints/approval/edit/$id': typeof AdminComplaintsApprovalEditIdRoute
  '/admin/settings/categories/edit/$id': typeof AdminSettingsCategoriesEditIdRoute
  '/admin/settings/roles/edit/$id': typeof AdminSettingsRolesEditIdRoute
  '/admin/settings/users/edit/$id': typeof AdminSettingsUsersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/SubmitComplaintRoute'
    | '/TrackComplaintRoute'
    | '/auth'
    | '/ComplaintDetailRoute/$id'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/complaints/assignment'
    | '/admin/complaints/documents'
    | '/admin/complaints/extensions'
    | '/admin/complaints/intake'
    | '/admin/complaints/investigation'
    | '/admin/complaints/sensitive'
    | '/admin/reports/audit-log'
    | '/admin/reports/executive'
    | '/admin/reports/investigation'
    | '/admin/reports/sla'
    | '/admin/reports/summary'
    | '/admin/settings/Term-Privacy'
    | '/admin/settings/audit-logs'
    | '/admin/settings/forms'
    | '/admin/settings/notifications'
    | '/admin/settings/organizations'
    | '/admin/settings/sla'
    | '/admin/settings/subcategories'
    | '/admin/complaints/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/complaints/edit/$id'
    | '/admin/settings/categories/new'
    | '/admin/settings/roles/new'
    | '/admin/settings/users/new'
    | '/admin/complaints/approval/'
    | '/admin/settings/categories/'
    | '/admin/settings/roles/'
    | '/admin/settings/users/'
    | '/admin/complaints/approval/edit/$id'
    | '/admin/settings/categories/edit/$id'
    | '/admin/settings/roles/edit/$id'
    | '/admin/settings/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/SubmitComplaintRoute'
    | '/TrackComplaintRoute'
    | '/auth'
    | '/ComplaintDetailRoute/$id'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/complaints/assignment'
    | '/admin/complaints/documents'
    | '/admin/complaints/extensions'
    | '/admin/complaints/intake'
    | '/admin/complaints/investigation'
    | '/admin/complaints/sensitive'
    | '/admin/reports/audit-log'
    | '/admin/reports/executive'
    | '/admin/reports/investigation'
    | '/admin/reports/sla'
    | '/admin/reports/summary'
    | '/admin/settings/Term-Privacy'
    | '/admin/settings/audit-logs'
    | '/admin/settings/forms'
    | '/admin/settings/notifications'
    | '/admin/settings/organizations'
    | '/admin/settings/sla'
    | '/admin/settings/subcategories'
    | '/admin/complaints'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/complaints/edit/$id'
    | '/admin/settings/categories/new'
    | '/admin/settings/roles/new'
    | '/admin/settings/users/new'
    | '/admin/complaints/approval'
    | '/admin/settings/categories'
    | '/admin/settings/roles'
    | '/admin/settings/users'
    | '/admin/complaints/approval/edit/$id'
    | '/admin/settings/categories/edit/$id'
    | '/admin/settings/roles/edit/$id'
    | '/admin/settings/users/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/SubmitComplaintRoute'
    | '/TrackComplaintRoute'
    | '/auth'
    | '/ComplaintDetailRoute/$id'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/complaints/assignment'
    | '/admin/complaints/documents'
    | '/admin/complaints/extensions'
    | '/admin/complaints/intake'
    | '/admin/complaints/investigation'
    | '/admin/complaints/sensitive'
    | '/admin/reports/audit-log'
    | '/admin/reports/executive'
    | '/admin/reports/investigation'
    | '/admin/reports/sla'
    | '/admin/reports/summary'
    | '/admin/settings/Term-Privacy'
    | '/admin/settings/audit-logs'
    | '/admin/settings/forms'
    | '/admin/settings/notifications'
    | '/admin/settings/organizations'
    | '/admin/settings/sla'
    | '/admin/settings/subcategories'
    | '/admin/complaints/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/complaints/edit/$id'
    | '/admin/settings/categories/new'
    | '/admin/settings/roles/new'
    | '/admin/settings/users/new'
    | '/admin/complaints/approval/'
    | '/admin/settings/categories/'
    | '/admin/settings/roles/'
    | '/admin/settings/users/'
    | '/admin/complaints/approval/edit/$id'
    | '/admin/settings/categories/edit/$id'
    | '/admin/settings/roles/edit/$id'
    | '/admin/settings/users/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubmitComplaintRouteRoute: typeof SubmitComplaintRouteRoute
  TrackComplaintRouteRoute: typeof TrackComplaintRouteRoute
  AuthRoute: typeof AuthRoute
  ComplaintDetailRouteIdRoute: typeof ComplaintDetailRouteIdRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminComplaintsAssignmentRoute: typeof AdminComplaintsAssignmentRoute
  AdminComplaintsDocumentsRoute: typeof AdminComplaintsDocumentsRoute
  AdminComplaintsExtensionsRoute: typeof AdminComplaintsExtensionsRoute
  AdminComplaintsIntakeRoute: typeof AdminComplaintsIntakeRoute
  AdminComplaintsInvestigationRoute: typeof AdminComplaintsInvestigationRoute
  AdminComplaintsSensitiveRoute: typeof AdminComplaintsSensitiveRoute
  AdminReportsAuditLogRoute: typeof AdminReportsAuditLogRoute
  AdminReportsExecutiveRoute: typeof AdminReportsExecutiveRoute
  AdminReportsInvestigationRoute: typeof AdminReportsInvestigationRoute
  AdminReportsSlaRoute: typeof AdminReportsSlaRoute
  AdminReportsSummaryRoute: typeof AdminReportsSummaryRoute
  AdminSettingsTermPrivacyRoute: typeof AdminSettingsTermPrivacyRoute
  AdminSettingsAuditLogsRoute: typeof AdminSettingsAuditLogsRoute
  AdminSettingsFormsRoute: typeof AdminSettingsFormsRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsOrganizationsRoute: typeof AdminSettingsOrganizationsRoute
  AdminSettingsSlaRoute: typeof AdminSettingsSlaRoute
  AdminSettingsSubcategoriesRoute: typeof AdminSettingsSubcategoriesRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminComplaintsEditIdRoute: typeof AdminComplaintsEditIdRoute
  AdminSettingsCategoriesNewRoute: typeof AdminSettingsCategoriesNewRoute
  AdminSettingsRolesNewRoute: typeof AdminSettingsRolesNewRoute
  AdminSettingsUsersNewRoute: typeof AdminSettingsUsersNewRoute
  AdminComplaintsApprovalIndexRoute: typeof AdminComplaintsApprovalIndexRoute
  AdminSettingsCategoriesIndexRoute: typeof AdminSettingsCategoriesIndexRoute
  AdminSettingsRolesIndexRoute: typeof AdminSettingsRolesIndexRoute
  AdminSettingsUsersIndexRoute: typeof AdminSettingsUsersIndexRoute
  AdminComplaintsApprovalEditIdRoute: typeof AdminComplaintsApprovalEditIdRoute
  AdminSettingsCategoriesEditIdRoute: typeof AdminSettingsCategoriesEditIdRoute
  AdminSettingsRolesEditIdRoute: typeof AdminSettingsRolesEditIdRoute
  AdminSettingsUsersEditIdRoute: typeof AdminSettingsUsersEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TrackComplaintRoute': {
      id: '/TrackComplaintRoute'
      path: '/TrackComplaintRoute'
      fullPath: '/TrackComplaintRoute'
      preLoaderRoute: typeof TrackComplaintRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SubmitComplaintRoute': {
      id: '/SubmitComplaintRoute'
      path: '/SubmitComplaintRoute'
      fullPath: '/SubmitComplaintRoute'
      preLoaderRoute: typeof SubmitComplaintRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ComplaintDetailRoute/$id': {
      id: '/ComplaintDetailRoute/$id'
      path: '/ComplaintDetailRoute/$id'
      fullPath: '/ComplaintDetailRoute/$id'
      preLoaderRoute: typeof ComplaintDetailRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/admin/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/admin/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/subcategories': {
      id: '/admin/settings/subcategories'
      path: '/admin/settings/subcategories'
      fullPath: '/admin/settings/subcategories'
      preLoaderRoute: typeof AdminSettingsSubcategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/sla': {
      id: '/admin/settings/sla'
      path: '/admin/settings/sla'
      fullPath: '/admin/settings/sla'
      preLoaderRoute: typeof AdminSettingsSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/organizations': {
      id: '/admin/settings/organizations'
      path: '/admin/settings/organizations'
      fullPath: '/admin/settings/organizations'
      preLoaderRoute: typeof AdminSettingsOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/admin/settings/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/forms': {
      id: '/admin/settings/forms'
      path: '/admin/settings/forms'
      fullPath: '/admin/settings/forms'
      preLoaderRoute: typeof AdminSettingsFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/audit-logs': {
      id: '/admin/settings/audit-logs'
      path: '/admin/settings/audit-logs'
      fullPath: '/admin/settings/audit-logs'
      preLoaderRoute: typeof AdminSettingsAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/Term-Privacy': {
      id: '/admin/settings/Term-Privacy'
      path: '/admin/settings/Term-Privacy'
      fullPath: '/admin/settings/Term-Privacy'
      preLoaderRoute: typeof AdminSettingsTermPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/summary': {
      id: '/admin/reports/summary'
      path: '/admin/reports/summary'
      fullPath: '/admin/reports/summary'
      preLoaderRoute: typeof AdminReportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/sla': {
      id: '/admin/reports/sla'
      path: '/admin/reports/sla'
      fullPath: '/admin/reports/sla'
      preLoaderRoute: typeof AdminReportsSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/investigation': {
      id: '/admin/reports/investigation'
      path: '/admin/reports/investigation'
      fullPath: '/admin/reports/investigation'
      preLoaderRoute: typeof AdminReportsInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/executive': {
      id: '/admin/reports/executive'
      path: '/admin/reports/executive'
      fullPath: '/admin/reports/executive'
      preLoaderRoute: typeof AdminReportsExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/audit-log': {
      id: '/admin/reports/audit-log'
      path: '/admin/reports/audit-log'
      fullPath: '/admin/reports/audit-log'
      preLoaderRoute: typeof AdminReportsAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/sensitive': {
      id: '/admin/complaints/sensitive'
      path: '/admin/complaints/sensitive'
      fullPath: '/admin/complaints/sensitive'
      preLoaderRoute: typeof AdminComplaintsSensitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/investigation': {
      id: '/admin/complaints/investigation'
      path: '/admin/complaints/investigation'
      fullPath: '/admin/complaints/investigation'
      preLoaderRoute: typeof AdminComplaintsInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/intake': {
      id: '/admin/complaints/intake'
      path: '/admin/complaints/intake'
      fullPath: '/admin/complaints/intake'
      preLoaderRoute: typeof AdminComplaintsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/extensions': {
      id: '/admin/complaints/extensions'
      path: '/admin/complaints/extensions'
      fullPath: '/admin/complaints/extensions'
      preLoaderRoute: typeof AdminComplaintsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/documents': {
      id: '/admin/complaints/documents'
      path: '/admin/complaints/documents'
      fullPath: '/admin/complaints/documents'
      preLoaderRoute: typeof AdminComplaintsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/assignment': {
      id: '/admin/complaints/assignment'
      path: '/admin/complaints/assignment'
      fullPath: '/admin/complaints/assignment'
      preLoaderRoute: typeof AdminComplaintsAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/users/': {
      id: '/admin/settings/users/'
      path: '/admin/settings/users'
      fullPath: '/admin/settings/users/'
      preLoaderRoute: typeof AdminSettingsUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/roles/': {
      id: '/admin/settings/roles/'
      path: '/admin/settings/roles'
      fullPath: '/admin/settings/roles/'
      preLoaderRoute: typeof AdminSettingsRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/categories/': {
      id: '/admin/settings/categories/'
      path: '/admin/settings/categories'
      fullPath: '/admin/settings/categories/'
      preLoaderRoute: typeof AdminSettingsCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/approval/': {
      id: '/admin/complaints/approval/'
      path: '/admin/complaints/approval'
      fullPath: '/admin/complaints/approval/'
      preLoaderRoute: typeof AdminComplaintsApprovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/users/new': {
      id: '/admin/settings/users/new'
      path: '/admin/settings/users/new'
      fullPath: '/admin/settings/users/new'
      preLoaderRoute: typeof AdminSettingsUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/roles/new': {
      id: '/admin/settings/roles/new'
      path: '/admin/settings/roles/new'
      fullPath: '/admin/settings/roles/new'
      preLoaderRoute: typeof AdminSettingsRolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/categories/new': {
      id: '/admin/settings/categories/new'
      path: '/admin/settings/categories/new'
      fullPath: '/admin/settings/categories/new'
      preLoaderRoute: typeof AdminSettingsCategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/edit/$id': {
      id: '/admin/complaints/edit/$id'
      path: '/admin/complaints/edit/$id'
      fullPath: '/admin/complaints/edit/$id'
      preLoaderRoute: typeof AdminComplaintsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/users/edit/$id': {
      id: '/admin/settings/users/edit/$id'
      path: '/admin/settings/users/edit/$id'
      fullPath: '/admin/settings/users/edit/$id'
      preLoaderRoute: typeof AdminSettingsUsersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/roles/edit/$id': {
      id: '/admin/settings/roles/edit/$id'
      path: '/admin/settings/roles/edit/$id'
      fullPath: '/admin/settings/roles/edit/$id'
      preLoaderRoute: typeof AdminSettingsRolesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/categories/edit/$id': {
      id: '/admin/settings/categories/edit/$id'
      path: '/admin/settings/categories/edit/$id'
      fullPath: '/admin/settings/categories/edit/$id'
      preLoaderRoute: typeof AdminSettingsCategoriesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints/approval/edit/$id': {
      id: '/admin/complaints/approval/edit/$id'
      path: '/admin/complaints/approval/edit/$id'
      fullPath: '/admin/complaints/approval/edit/$id'
      preLoaderRoute: typeof AdminComplaintsApprovalEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmitComplaintRouteRoute: SubmitComplaintRouteRoute,
  TrackComplaintRouteRoute: TrackComplaintRouteRoute,
  AuthRoute: AuthRoute,
  ComplaintDetailRouteIdRoute: ComplaintDetailRouteIdRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminComplaintsAssignmentRoute: AdminComplaintsAssignmentRoute,
  AdminComplaintsDocumentsRoute: AdminComplaintsDocumentsRoute,
  AdminComplaintsExtensionsRoute: AdminComplaintsExtensionsRoute,
  AdminComplaintsIntakeRoute: AdminComplaintsIntakeRoute,
  AdminComplaintsInvestigationRoute: AdminComplaintsInvestigationRoute,
  AdminComplaintsSensitiveRoute: AdminComplaintsSensitiveRoute,
  AdminReportsAuditLogRoute: AdminReportsAuditLogRoute,
  AdminReportsExecutiveRoute: AdminReportsExecutiveRoute,
  AdminReportsInvestigationRoute: AdminReportsInvestigationRoute,
  AdminReportsSlaRoute: AdminReportsSlaRoute,
  AdminReportsSummaryRoute: AdminReportsSummaryRoute,
  AdminSettingsTermPrivacyRoute: AdminSettingsTermPrivacyRoute,
  AdminSettingsAuditLogsRoute: AdminSettingsAuditLogsRoute,
  AdminSettingsFormsRoute: AdminSettingsFormsRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsOrganizationsRoute: AdminSettingsOrganizationsRoute,
  AdminSettingsSlaRoute: AdminSettingsSlaRoute,
  AdminSettingsSubcategoriesRoute: AdminSettingsSubcategoriesRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminComplaintsEditIdRoute: AdminComplaintsEditIdRoute,
  AdminSettingsCategoriesNewRoute: AdminSettingsCategoriesNewRoute,
  AdminSettingsRolesNewRoute: AdminSettingsRolesNewRoute,
  AdminSettingsUsersNewRoute: AdminSettingsUsersNewRoute,
  AdminComplaintsApprovalIndexRoute: AdminComplaintsApprovalIndexRoute,
  AdminSettingsCategoriesIndexRoute: AdminSettingsCategoriesIndexRoute,
  AdminSettingsRolesIndexRoute: AdminSettingsRolesIndexRoute,
  AdminSettingsUsersIndexRoute: AdminSettingsUsersIndexRoute,
  AdminComplaintsApprovalEditIdRoute: AdminComplaintsApprovalEditIdRoute,
  AdminSettingsCategoriesEditIdRoute: AdminSettingsCategoriesEditIdRoute,
  AdminSettingsRolesEditIdRoute: AdminSettingsRolesEditIdRoute,
  AdminSettingsUsersEditIdRoute: AdminSettingsUsersEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
