export {
  getComplaintStatusVariant,
  getComplaintPriorityVariant,
  getIntakeStatusVariant,
  getAssignmentStatusVariant,
  getApprovalStatusVariant,
  getInvestigationStatusVariant,
  getDocumentStatusVariant,
  getSensitiveStatusVariant,
  getAuditLogStatusVariant,
  getReportStatusVariant,
  getAuditReportStatusVariant,
  getExecutiveReportStatusVariant,
  getSLAReportStatusVariant,
  getInvestigationReportStatusVariant,
  getFormStatusVariant,
} from "./status";
